# Node.js with Angular
# Build a Node.js project that uses Angular.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- task: Npm@1
  displayName: 'npm install'
  inputs:
    verbose: false
- task: Npm@1
  displayName: 'npm build'
  inputs:
    command: custom
    verbose: false
    customCommand: 'run build'
    
- task: ArchiveFiles@2
  displayName: 'Archive files'
  inputs:
    rootFolderOrFile: dist/skills-management-app
    includeRootFolder: false
- task: PublishBuildArtifacts@1
  displayName: 'Publish artifacts: drop'


- task: AzureRmWebAppDeployment@4
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'Free Trial(4f771507-356a-4bff-afe4-d2bda014d8cc)'
    appType: 'webApp'
    WebAppName: 'skills-management'
    packageForLinux: '$(System.DefaultWorkingDirectory)/**/*.zip'